### ISSUE TITLE
Error reading input value for Extension "Biomass Harvest"

### ISSUE THREAD

**Issue by ppettus** [LANDIS-II-Foundation/Extension-Biomass-Harvest#39]
Installer created these four files:

Landis.Extension.BiomassHarvest-v4-BiomassRank.dll
Landis.Extension.BiomassHarvest-v4-BiomassRank.pdb
Landis.Library.HarvestManagement-v3-Biomass.dll
Landis.Library.HarvestManagement-v3-Biomass.pdb

In the scenario file we have:

"Biomass Harvest"	FB_Harvest_BAU_042519.txt

Loading scenario from file "scenario_FB.txt" ...
Error at line 36 of file "scenario_FB.txt":
  Error reading input value for Extension:
    No extension with the name "Biomass Harvest".

![Error_message](https://user-images.githubusercontent.com/35970676/56918844-f2df1400-6a73-11e9-86d9-7f1da4cbfd7d.PNG)

**Comment by rmscheller** [comment]
Paul,
Did you install: https://github.com/LANDIS-II-Foundation/Extension-Biomass-Harvest/blob/biomass-ranking/deploy/installer/LANDIS-II-V7%20Biomass%20Harvest%20Biomass%20Rank%204.0-setup.exe

?

**Comment by ppettus** [comment]
Yes.

P

**Comment by rmscheller** [comment]
This branch needs to be referenced as "Biomass Harvest Biomass Rank".  See: https://github.com/LANDIS-II-Foundation/Extension-Biomass-Harvest/blob/biomass-ranking/testings/Core7-BiomassHarvest-BiomassRank/scenario.txt
