### ISSUE TITLE
Double the biomass is being removed in a clearcut or thin

### ISSUE THREAD

**Issue by ppettus** [LANDIS-II-Foundation/Extension-Biomass-Harvest#40]
While running the latest "Biomass Harvest Biomass" and NECN together, double the biomass is being removed and reported in the logs and biomass-harverst maps.  These values are double the ones seen in the year to year changes in the biomass maps. Example the difference between, biomass year 0 map, clearcut, biomass year 1 map, equals 1000 MG. Biomass harvest log and biomass-removed both show 2000MG removed.

**Comment by rmscheller** [comment]
Austen,
Where does the MarkCohorts function in biomass harvest live?  What library?  Does the function return a double (a fraction) or an int (the total biomass)?  If I knew where to find it, I could figure this out but I am always and utterly baffled by the harvest libraries.  Thanks!

Rob

**Comment by aruzicka555** [comment]
Rob,

MarkCohorts is in Library-Biomass-Cohort. It returns an int and the comments note that this is the "total of all the cohorts' biomass reductions".

The harvest libraries are laid out like so: there are the two main libraries Base and Biomass-Harvest. They both have (mostly) the same extraneous libraries like Library-Cohorts, Library-Succession, Library-Harvest-Management etc. Base and Biomass-Harvest hardly do any real work, they mostly just log information and run the harvests. They call on these extraneous libraries to do most of the calculations and work. Library-Harvest-Management is where most of the heavy lifting is done for harvest and it is usually the best place to look first.

**Comment by rmscheller** [comment]
Thanks, Austen.  

Paul, could you set up a single cell scenario that highlights the issue you're having?  Debugging isn't possible on anything larger.   To start, see:  https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/tree/master/testing/NECN_Tina_SingleCell_loblolly

**Comment by rmscheller** [comment]
This should be resolved with merge pull request #49
