### ISSUE TITLE
Plant keyword error

### ISSUE THREAD

**Issue by TinaGM** [LANDIS-II-Foundation/Extension-Biomass-Harvest#42]
When I try to run Biomass Harvest with the **Plant** keyword in the text file it throws a stack trace error saying "Object reference not set to an instance of an object". The stack trace seems to come from Landis. Library. Succession. Reproduction. ScheduleForPlanting (SpeciesList speciesToPlant, ActiveSite site). I've tried to do some double checking on my end to make sure this isn't an error that I've made in my management or stand maps or in the harvest text file itself. None of the fixes I've made have made a difference and at this point I think it's worth looking into the code to make sure the error isn't there. Thank you!

![Plant stack trace error](https://user-images.githubusercontent.com/42039902/60365685-67242e00-99b7-11e9-8bad-89b8ed148441.PNG)

**Comment by TinaGM** [comment]
Any update on this issue?

**Comment by rmscheller** [comment]
Testing indicates that this has been resolved with the latest release.
