### ISSUE TITLE
Columns name for log file

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Harvest#6]
From Matthew Duveneck:  I suggest that the spaced be eliminated in the column names in the harvest_log.csv and the harvest_summary.csv.  For example, currently column names read "speciesname (cohorts)" and "speciesname (Mg)".   An underscore would make these files much easier to use (e.g. "speciesname_cohorts" and "speciesname_Mg") with R or other stats packages.

**Comment by lbross** [comment]
From Eric G: Yes, removing spaces is very helpful.  I just would like to see units added somehow.

**Comment by lbross** [comment]
I will implement Matthew's suggestion of replacing spaces with underscores_ in the column headers. Eric is out until October 5 but I hopefully we can release Harvest extensions v3.0 shortly after his return, including this issue.

**Comment by lbross** [comment]
Matthew verified. Fixed in v3.0
