### ISSUE TITLE
Extra comma at the end of harvest_log

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Harvest#8]
There is an extra comma at the end of the data rows in harvest_log.csv.  This is causing problem when reading into R.

**Comment by lbross** [comment]
This is a problem with Base Harvest as well.

**Comment by lbross** [comment]
This is fixed in v3.0 rc6. There is an installer available for download/testing at https://github.com/LANDIS-II-Foundation/Extension-Biomass-Harvest/releases/tag/v3.0-rc6.

This is also fixed in Base Harvest v3.0 rc4.

**Comment by lbross** [comment]
Verified by Matthew. Released in v3.0/
